package com.pppjpademo.jpa;

import lombok.*;

import javax.persistence.*;

@Entity
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString(exclude = "product")
public class OrderItem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private int quantity;


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false) // OrderItem 테이블의 FK
    /*
     create table OrderItem (
       id bigint generated by default as identity,
        quantity integer not null,
        product_id bigint,
        primary key (id)
     )
     alter table OrderItem 
       add constraint FKg23j1vs750x8lkx2aesfk6n2 
       foreign key (product_id) 
       references Product
     */
    private Product product;
    // OrderItem에 product 테이블의 포리진 키를 만들껀데 private 이다
    // 값은 절대 null 일수없다 -> 무결성 제약 조건 위배
    // OrderItem 만 Product 엔티티 클래스를 참조하고 있음
    // -> 단방향이라 한다
    
    public OrderItem(Product product, int quantity) {
        this.product = product;
        this.quantity = quantity;
    }

    public void changeProduct(Product newProduct) {
        this.product = newProduct;
    }
}
